### ISSUE TITLE
Could not invoke "CustomTabsManager.openURL

### ISSUE THREAD

**Issue by lateef4web** [droibit/react-native-custom-tabs#6] opened 2017-03-30 23:22 UTC
Hi @droibit ! and thanks for this module, is very useful.
I got the following error when i tried to launch the browser, after installing 'react-native-paystack' SDK;

![screenshot_2017-03-31-00-06-46](https://cloud.githubusercontent.com/assets/13805954/24530159/0f339eb4-15a8-11e7-99b1-296c8ad4b32b.png)

Please Help!

**Comment by droibit** [comment] 2017-04-02 08:05
@lateef4web 
I think that `react-native-custom-tabs` depends on `old react-native`.  
Just released the new module which supported the latest 0.42.3.
Please try updating the module.

**Comment by mzmiric5** [comment] 2017-04-02 15:58
@droibit this still seems to be an issue. I'm running RN 0.42.3 and 0.1.4 and still getting the same error message.

**Comment by droibit** [comment] 2017-04-02 16:14
@mzmiric5 
Hmm... can you share the code to confirm this error?

**Comment by lateef4web** [comment] 2017-04-02 16:51
@droibit i'm still getting the same error. Could you please test with 'react-native-paystack' SDK. Thanks.

**Comment by mzmiric5** [comment] 2017-04-02 17:22
@droibit trying to get a minimal repro project on github, since the original project is closed source. I have managed to isolate the issue to including react-native-intercom (or the actual intercom library). As soon as I remove it, the error goes away. So it seems to be some kind of an incompatibility between the two. would be interesting to know if @lateef4web also uses intercom in their app

**Comment by lateef4web** [comment] 2017-04-02 17:26
The problem started when i installed 'react-native-paystack'. I don't use intercom. But the problem goes away when i remove 'react-native-paystack'. Could you please debug with 'react-native-paystack' sdk. 

Thanks.

**Comment by mzmiric5** [comment] 2017-04-02 17:55
@droibit here's a minimum repro needed to cause it to have this issue on android when using intercom https://github.com/mzmiric5/RN-CustomTabs-Intercom-Error

**Comment by lateef4web** [comment] 2017-04-02 18:03
@droibit i don't use intercom, but i guess they both reproduce same issue. Please what is the way forward?
Thanks.

**Comment by mzmiric5** [comment] 2017-04-02 18:10
@droibit as a possible link between the two, both intercom and paystack use com.android.support:appcompat-v7:25.0.1 that gets shared with the main app. I assume this probably overwrites your use of v7:23 and I guess the v7:25 handles activity starting differently?

**Comment by droibit** [comment] 2017-04-03 02:37
@mzmiric5 
> > I assume this probably overwrites your use of v7:23 and I guess the v7:25 handles activity starting
differently?
>
> Probably, I think it is the same behavior.
> I guess that the interface or behavior of support-customtabs has changed.

The cause of this error was as you expected!  
Activity starting method was different in `support-customtabs` in v23 and v25.  

So, `react-native-custom-tabs` updates to support `support-customtabs` of the latest version `25.3.1`.  
I'm going to release the module that fixed this issue today.

Thank you!

**Comment by mzmiric5** [comment] 2017-04-03 08:15
can confirm this resolved the issue with rn-intercom, awaiting the npm release. Thanks for resolving this quickly :)

**Comment by droibit** [comment] 2017-04-03 10:59
I just published the latest version of 0.1.5.

@mzmiric5 
Your cooperation is really appreciated 👍 

@lateef4web 
Please try updating the module.

**Comment by lateef4web** [comment] 2017-04-03 11:16
Thanks @droibit, working now.

**Closed** 2017-04-04 01:35 UTC
